[window]
decorations = "Full"
# padding = { x = 10, y = 10 }
opacity = 0.95

[terminal]
shell = "/home/doanh/.cargo/bin/nu"

[font]
size = 13

[font.normal]
family = "JetBrainsMono Nerd Font"

[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = true

[colors.primary]
background = "#173448"
foreground = "#ffffff"

[colors.normal]
black   = "#000000"
red     = "#ff2600"
green   = "#3cdf2b"
yellow  = "#f4d300"
blue    = "#1478db"
magenta = "#ff2c70"
cyan    = "#00c5c7"
white   = "#c7c7c7"

[colors.bright]
black   = "#686868"
red     = "#f92a1c"
green   = "#43d426"
yellow  = "#f1d000"
blue    = "#6871ff"
magenta = "#ff77ff"
cyan    = "#79e8fb"
white   = "#ffffff"

[colors.cursor]
text   = "#feffF4"
cursor = "#f4d300"

[colors.selection]
text       = "CellForeground"
background = "#1f4562"
