# Window
window_padding_width 0
hide_window_decorations no
background_opacity 0.95

# Shell
shell /home/doanh/.cargo/bin/nu

# Font
font_family JetBrainsMono Nerd Font
font_size 13.0

# Cursor
cursor_blink_interval 0
shell_integration no-cursor

# Scrollback
scrollback_lines 10000

# Mouse
copy_on_select clipboard
mouse_hide_wait 3.0

# Tab bar
tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style slanted

# Key mappings
map ctrl+shift+t new_tab_with_cwd
map ctrl+shift+n new_os_window_with_cwd

# Performance
repaint_delay 10
input_delay 3

# Wayland
wayland_titlebar_color background
linux_display_server wayland

# Touchscreen
touch_scroll_multiplier 1

# ===== Colors =====

# Background and foreground
background #173448
foreground #ffffff

# Normal colors
color0 #000000
color1 #ff2600
color2 #3cdf2b
color3 #f4d300
color4 #1478db
color5 #ff2c70
color6 #00c5c7
color7 #c7c7c7

# Bright colors
color8 #686868
color9 #f92a1c
color10 #43d426
color11 #f1d000
color12 #6871ff
color13 #ff77ff
color14 #79e8fb
color15 #ffffff

# Cursor
cursor #f4d300
cursor_text_color #fefff4

# Selection
selection_background #1f4562
