# Entry point for the nushell config.
#
# `~/.config/nushell/config.nu` is generated by home-manager (home.nix) and
# only does `source <dotfiles>/nushell/my.nu`, so this file is the single
# source of truth. Files are kept separate so each one stays focused:
#   init.nu    - theme, carapace, starship
#   env.nu     - environment variables and PATH
#   aliases.nu - aliases and small helper commands
#   tools.nu   - interactive tool startup (zellij)
#
# NOTE: env.nu must be sourced before init.nu/aliases.nu so PATH and
# EDITOR/SHELL are set before anything that depends on them runs.
source ./env.nu
source ./init.nu
source ./aliases.nu
source ./tools.nu
