theme = "monokai_pro_spectrum"

[editor]
line-number = "relative"
end-of-line-diagnostics = "hint"
completion-trigger-len = 0
bufferline = "always"

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.lsp]
auto-signature-help = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
